services:
  build:
    build:
      context: .
      target: build

  publish:
    build:
      context: .
      target: publish
    depends_on:
      - docs

  docs:
    build:
      context: .
      target: docs
    depends_on:
      - build
    ports:
      - "1117:80"
